### ISSUE TITLE
4号機の使い方とか...

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT/fourth_robot_pkg#23]
@tanacchi 
最近4号機を使おうとしてくれているようなので、わからないこととかあったらIssueで聞いてください！
どんな些細なことでもおｋなので、よろしく！
とりあえずの注意点（身の危険があること）を挙げときます。
### 配線について
電源部分、蛸足部分、直列、並列、すべてのコネクタの形状が同じです...(o0o)
正直、さし間違えたりするとショートします...
素子が壊れることはもちろん、感電、電池の爆発も考えられます...
僕一人のときでもよくわからなくなってました...OMG
十分注意して、改造するときはやってください。
わかんなかったら即聞いてください！！！
もしコネクタをきれいにしようとかいう野望をお持ちなら、種類の違うコネクタをいくつか買ってきて、さし間違えが起きないように工夫してみてください。
僕のケツ拭いてもらうことになってホントすみません。

### 機体について
機体は見てのとおりアルミフレームで作ってあります。
思ってるより、洋服を引っ掛けて穴を開けることになります。
覚悟するorつなぎでも買ってやってみてください。
組み立てとかすると、思ってるより手に引っかき傷などの生傷が増えます。
薄手の手袋などもあると良いでしょう。

### マシンの発進・操縦について
このGithubにあがっている最新のdriverを使っている限り起こらないと思いますが、電源につないだ状態で緊急停止スイッチを開放すると、ロボットが暴走することがあります。
緊急停止スイッチを開放するときは、十分注意して執り行ってください...
操縦に関しては、無線モードのとき、途中でBluetoothの信号が切れたりすると、場合によっては最後の入力が入りっぱなしになります。十分注意してください。

以上、よろしくお願いします！！

**Comment by tanacchi** [comment]
ありがとうございます！！！😭
現在5/20の九工大チャレンジに向けて、とりあえず機体を動かせる状態にしているところです。
モータードライバを入れるところで少々つまづいている状況です。
ハード・ソフトともに、本格的にいじるのはそれ以降になりそうです。その時はよろしくお願いします🤲

**Comment by RyodoTanaka** [comment]
@tanacchi 
あぁ，モータードライバか！！
あれは，カーネルのバージョンによって少しソースコードを書き換えてからコンパイルせんといかんので，今日の夜（10時とか）に資料をupします！

**Comment by tanacchi** [comment]
ありがとうございます！！お願いします

**Comment by RyodoTanaka** [comment]
@tanacchi 
https://github.com/CIR-KIT/fourth_robot_pkg/wiki
Wikiページ作ったので読んでやってみてください！
自分が新たに得た知識などはどんどんwikiに書き足していってくださいm(_ _)m
わかんないところがあれば，
1. Issueを立てる
2. とりあえず解決を目指す
3. 解決したらwikiにIssueのリンクとともに内容を記載する

という手順でおねがいしますm(_ _)m
そうすると，後輩と僕がとても助かります．
よろしく！！！

**Comment by tanacchi** [comment]
ありがとうございます！！！🙏
頑張ってみます！
