### ISSUE TITLE
モータードライバモジュールが入らない

### ISSUE THREAD

**Issue by tanacchi** [CIR-KIT/fourth_robot_pkg#24]
対処法をご存知でしたらお教え願います。orz
## 概要
wiki の[このページ](https://github.com/CIR-KIT/fourth_robot_pkg/wiki/iMCs01%E3%83%89%E3%83%A9%E3%82%A4%E3%83%90%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%A8%E6%8E%A5%E7%B6%9A%E6%96%B9%E6%B3%95 "wiki")にしたがって作業を進めていましたが、
どうも上手くカーネルモジュールのロード(`insmod`)まで上手くいきません。

### @tanacchi のパソコン 
OS: Ubuntu 16.04
Kernel バージョン: 4.13.0-41-generic
**makeの段階でエラーが吐かれます。**
![make_error](https://user-images.githubusercontent.com/19949534/39990220-02d88c0a-57a7-11e8-8d74-9b0ae3f221c1.png)
imcs01 自体が古いようなので、16.04 では厳しいかとも思っていますが
configureを書いたら上手くいくかもと期待しながら対処しています。

###  @Kose-i のパソコン
OS: Ubuntu 14.04
Kernel バージョン:  4.4.0-124-generic
**insmodの段階で`Required key not available`とエラーが吐かれます。**
![insmod_error](https://user-images.githubusercontent.com/29277654/39990975-0561b238-57a9-11e8-857d-15e760494975.png)
usb に imcs01 を接続しても`/dev/urbtc*`は存在しませんでした。
こちらも試行錯誤しながら対処しています。

どちらも `urbtc.c` のinclude 部分を書き換えています。

**Comment by RyodoTanaka** [comment]
@tanacchi 
Ubuntu 16.04で起きるエラーですが，確かに僕のPC（ubuntu 16.04 Kernel 4.0.13.0-36）でも同様のエラーが置きました．軽くググッてみると，「4.0.10より古ければ...」みたいな記述を見つけたので，同じPC内にあった`4.0.4.0-124`を試したのですが，同様のエラーが出てしまいました...orz
何か対策を打たないとUbuntu 16.04では使えないですね....OMG

@Kose-i のPCについて
おそらく，`urbtc.ko`までのPathが通ってないことが原因のように思います．（本当に`urbtc.ko`が生成できているなら）
用意しているスクリプトでは，`rosfind`コマンドを利用しています．
故に，`fourth_robot_driver`までのPathが通っていないとうまく機能しません．
`fourth_robot_driver`パッケージを格納しているワークスーペースのPath通し（`source devel/setup.bash`ってするやつ）はきちんとできていますか？
確認をしてみてください．
よろしくお願いします．

**Comment by tanacchi** [comment]
Ubuntu 16.04 の件、了解しました。

確認してみたところ、Path は通っていました。

**Comment by RyodoTanaka** [comment]
Path通ってるのにうまくいかないのは初めてかも...
今すごい簡単に調べたら，BIOSのセキュアブートが有効になってるとinsmodできないことがあるみたい．
http://www.taillook.tech/entry/2016/11/02/115214
確かに，僕が使ってたLaptopはLegacyでブートしてたので，セキュアブートとかなかったから出会ってなかったエラーかもしれないです．
@Kose-i セキュアブートを無効にして試してみてもらってもいいですか？

**Comment by tanacchi** [comment]
セキュアブートを無効にするとうまくいきました！！！！！！！！！！！
ありがとうございました(;O;)
詳細は wikiに記載します
