### ISSUE TITLE
メインブランチとPRについて

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT/fourth_robot_pkg#26]
@tanacchi 
今`indigo-devel`ブランチを作ってそこでTravisを使ったCIテスト駆動ができるようにしてあります．
で，できれば今後何かPR(プルリクエスト)をマージする際は，CIテストがきちんと通ってから行うようにしてもらえると嬉しいです．
CIテストについては，コミットした時点とPRを行った時点で自動でテストが開始されます．
（素晴らしいことに，PRをマージした時にうまく動くかどうかまでテストしてくれる！）
で，結果もGithub上で確認できるようになっているので，それらがすべてうまく行っている（Passしている）場合のみPRをマージするようにしていただけるとありがたいです．
よろしく！！

**Comment by RyodoTanaka** [comment]
@tanacchi 
あと，メインブランチが今`master`になってると思うんやけど，`indigo-devel`をメインブランチにしませんか？
kineticで`urbtc`がビルドできない問題を解決すれば`kinetic-devel`をメインブランチにすれば良いとは思います．
よろしくお願いします！

**Comment by tanacchi** [comment]
上の件、了解しました。

**Comment by RyodoTanaka** [comment]
@tanacchi 
ありがとう！
では，`indigo-devel`を当面のメインブランチとしますね．

あ，そういえば
submoduleを使って依存パッケージ（wstoolじゃないと入らないやつ）を引っ張ってきているみたいやけど，wstool使うやり方じゃなんか不具合あった？

**Comment by tanacchi** [comment]
`*.rosinstall` ファイルの使い方を知らなかったのと、5号機のやり方に合わせようとしたので
`submodule`のほうに切り替えようとしていました。
後でwstoolを使ってみたら問題なく動いたので、実際どちらでもいいかなという感じです。

**Comment by RyodoTanaka** [comment]
@tanacchi 
なるほど
了解です．
