### ISSUE TITLE
モータードライバ移行案

### ISSUE THREAD

**Issue by tanacchi** [CIR-KIT/fourth_robot_pkg#27]
@RyodoTanaka 

#24 の後日談ですが、結局動かせなかったので、電装系のトラブルシューティングを行っていました。
しかし、それでも大きな欠陥も見られなかったのでやはりシステムのコアな部分で不具合が生じていると考えられます。

そこで、iMCs01を廃止にして他のモータードライバを購入する
もしくは自分らでドライバを書くという案が出たのですが、どうでしょうか？
あるいは、どちらが良いと思われますか？

**Comment by RyodoTanaka** [comment]
@tanacchi 
どっちも大変なことに変わりはなさそうですね...
### iMCs01じゃない奴使う場合
とりあえずAki-H8(おそらくAki-H8-3480)の外部カウンタがついてる奴を選べば問題ないと思われる．
#### メリット
僕が何をしたら良いのかわかってるので，手助けできそう．
組み込み系をやっとくのは吉．

#### デメリット
現在．I-P制御器が組んであるが，僕がかいたクソソースコードを読まないといけなくなる．

### 自分でモジュールプログラム書く場合
#### メリット
ハードウェアの変更はなさそう

#### デメリット
僕は何したらよいのかさっぱりわかりません（泣）

以上です．
個人的には前々からAki-H8使いたかったし，勉強にもなるから前者をおすすめします．

**Comment by tanacchi** [comment]
貴重なご意見、ありがとうございます！
またメンバーと話し合って決定したいと思います。

**Comment by tanacchi** [comment]
閉じます
